region: eu-central-1

vpc:
  securityGroupIds:
    - sg-09004f60
  subnetIds:
    - subnet-9430add9
    - subnet-0568d2ff5c9035631

apiGatewayAliasUrl: app.adesaglobal.com
apiBasePath: awsservice
apiGatewayDescription: awsservice Gateway

gatewayResponseAllowOrigin: https://adesaglobal.com
gatewayResponseAllowHeaders: Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token
gatewayResponseAllowMethods: GET,POST,PATCH,DELETE,PUT,OPTIONS
